// Compagnie aeree: [IATA, nome, titolo pagina Wikipedia, CC]
// L'elenco è scritto a mano (OurAirports non distribuisce le compagnie) ma non
// è dato per buono: il generatore prende il designatore IATA dall'infobox di
// Wikipedia e segnala le discrepanze con il codice qui annotato. Il codice
// serve quindi come controllo, non come dato.
const AIRLINES = [
  // ── Italia ──
  ['AZ', 'ITA Airways', 'ITA Airways', 'IT'],
  ['FR', 'Ryanair', 'Ryanair', 'IE'],
  ['U2', 'easyJet', 'easyJet', 'GB'],
  ['VY', 'Vueling', 'Vueling', 'ES'],
  ['W6', 'Wizz Air', 'Wizz Air', 'HU'],
  ['EN', 'Air Dolomiti', 'Air Dolomiti', 'IT'],
  ['CT', 'Alitalia CityLiner', 'Alitalia CityLiner', 'IT'],
  ['4B', 'Boutique Airlines', 'Boutique Airlines', 'IT'],
  // ── Europa ──
  ['BA', 'British Airways', 'British Airways', 'GB'],
  ['VS', 'Virgin Atlantic', 'Virgin Atlantic', 'GB'],
  ['LS', 'Jet2.com', 'Jet2.com', 'GB'],
  ['DY', 'Norwegian', 'Norwegian Air Shuttle', 'NO'],
  ['SK', 'SAS', 'Scandinavian Airlines', 'SE'],
  ['AY', 'Finnair', 'Finnair', 'FI'],
  ['TP', 'TAP Air Portugal', 'TAP Air Portugal', 'PT'],
  ['LX', 'SWISS', 'Swiss International Air Lines', 'CH'],
  ['OS', 'Austrian Airlines', 'Austrian Airlines', 'AT'],
  ['SN', 'Brussels Airlines', 'Brussels Airlines', 'BE'],
  ['KL', 'KLM', 'KLM', 'NL'],
  ['AF', 'Air France', 'Air France', 'FR'],
  ['TO', 'Transavia France', 'Transavia France', 'FR'],
  ['HV', 'Transavia', 'Transavia', 'NL'],
  ['UU', 'Air Europa', 'Air Europa', 'ES'],
  ['LO', 'LOT Polish Airlines', 'LOT Polish Airlines', 'PL'],
  ['OK', 'Czech Airlines', 'Czech Airlines', 'CZ'],
  ['RO', 'TAROM', 'TAROM', 'RO'],
  ['JU', 'Air Serbia', 'Air Serbia', 'RS'],
  ['A3', 'Aegean Airlines', 'Aegean Airlines', 'GR'],
  ['OU', 'Croatia Airlines', 'Croatia Airlines', 'HR'],
  ['KM', 'Air Malta', 'Air Malta', 'MT'],
  ['EW', 'Eurowings', 'Eurowings', 'DE'],
  ['LH', 'Lufthansa', 'Lufthansa', 'DE'],
  ['DE', 'Condor', 'Condor Flugdienst', 'DE'],
  // ── Turchia, Russia, Medio Oriente, Africa ──
  ['TK', 'Turkish Airlines', 'Turkish Airlines', 'TR'],
  ['PC', 'Pegasus Airlines', 'Pegasus Airlines', 'TR'],
  ['SU', 'Aeroflot', 'Aeroflot', 'RU'],
  ['S7', 'S7 Airlines', 'S7 Airlines', 'RU'],
  ['A9', 'Georgian Airways', 'Georgian Airways', 'GE'],
  ['FV', 'Rossiya Airlines', 'Rossiya Airlines', 'RU'],
  ['EK', 'Emirates', 'Emirates Airline', 'AE'],
  ['QR', 'Qatar Airways', 'Qatar Airways', 'QA'],
  ['EY', 'Etihad Airways', 'Etihad Airways', 'AE'],
  ['FZ', 'flydubai', 'flydubai', 'AE'],
  ['RJ', 'Royal Jordanian', 'Royal Jordanian Airlines', 'JO'],
  ['GF', 'Gulf Air', 'Gulf Air', 'BH'],
  ['SV', 'Saudia', 'Saudia', 'SA'],
  ['WY', 'Oman Air', 'Oman Air', 'OM'],
  ['KU', 'Kuwait Airways', 'Kuwait Airways', 'KW'],
  ['MS', 'EgyptAir', 'EgyptAir', 'EG'],
  ['AT', 'Royal Air Maroc', 'Royal Air Maroc', 'MA'],
  ['ET', 'Ethiopian Airlines', 'Ethiopian Airlines', 'ET'],
  ['KQ', 'Kenya Airways', 'Kenya Airways', 'KE'],
  ['SA', 'South African Airways', 'South African Airways', 'ZA'],
  // ── Nord America ──
  ['AA', 'American Airlines', 'American Airlines', 'US'],
  ['UA', 'United Airlines', 'United Airlines', 'US'],
  ['DL', 'Delta Air Lines', 'Delta Air Lines', 'US'],
  ['AS', 'Alaska Airlines', 'Alaska Airlines', 'US'],
  ['B6', 'JetBlue', 'JetBlue', 'US'],
  ['NK', 'Spirit Airlines', 'Spirit Airlines', 'US'],
  ['F9', 'Frontier Airlines', 'Frontier Airlines', 'US'],
  ['WN', 'Southwest Airlines', 'Southwest Airlines', 'US'],
  ['AC', 'Air Canada', 'Air Canada', 'CA'],
  ['WS', 'WestJet', 'WestJet', 'CA'],
  ['AM', 'Aeroméxico', 'Aeromexico', 'MX'],
  ['Y4', 'Volaris', 'Volaris', 'MX'],
  // ── Sud America ──
  ['LA', 'LATAM Airlines', 'LATAM Airlines', 'CL'],  ['AR', 'Aerolíneas Argentinas', 'Aerolíneas Argentinas', 'AR'],
  ['AV', 'Avianca', 'Avianca', 'CO'],
  ['CM', 'Copa Airlines', 'Copa Airlines', 'PA'],
  ['G3', 'Gol Linhas Aéreas', 'Gol Linhas Aéreas', 'BR'],
  ['AD', 'Azul', 'Azul Brazilian Airlines', 'BR'],
  // ── Asia ──
  ['JL', 'Japan Airlines', 'Japan Airlines', 'JP'],
  ['NH', 'ANA', 'All Nippon Airways', 'JP'],
  ['KE', 'Korean Air', 'Korean Air', 'KR'],
  ['OZ', 'Asiana Airlines', 'Asiana Airlines', 'KR'],
  ['CI', 'China Airlines', 'China Airlines', 'TW'],
  ['BR', 'EVA Air', 'EVA Air', 'TW'],
  ['CX', 'Cathay Pacific', 'Cathay Pacific', 'HK'],
  ['SQ', 'Singapore Airlines', 'Singapore Airlines', 'SG'],
  ['TR', 'Scoot', 'Scoot', 'SG'],
  ['MH', 'Malaysia Airlines', 'Malaysia Airlines', 'MY'],
  ['D7', 'AirAsia', 'AirAsia', 'MY'],
  ['TG', 'Thai Airways', 'Thai Airways International', 'TH'],
  ['FD', 'Thai AirAsia', 'Thai AirAsia', 'TH'],
  ['VN', 'Vietnam Airlines', 'Vietnam Airlines', 'VN'],
  ['AI', 'Air India', 'Air India', 'IN'],
  ['6E', 'IndiGo', 'IndiGo', 'IN'],
  ['UL', 'SriLankan Airlines', 'SriLankan Airlines', 'LK'],
  ['GA', 'Garuda Indonesia', 'Garuda Indonesia', 'ID'],
  ['PR', 'Philippine Airlines', 'Philippine Airlines', 'PH'],
  ['5J', 'Cebu Pacific', 'Cebu Pacific', 'PH'],
  ['9C', 'Spring Airlines', 'Spring Airlines', 'CN'],
  ['MU', 'China Eastern Airlines', 'China Eastern Airlines', 'CN'],
  ['CA', 'Air China', 'Air China', 'CN'],
  ['CZ', 'China Southern Airlines', 'China Southern Airlines', 'CN'],
  ['HU', 'Hainan Airlines', 'Hainan Airlines', 'CN'],
  // ── Oceania ──
  ['QF', 'Qantas', 'Qantas', 'AU'],
  ['NZ', 'Air New Zealand', 'Air New Zealand', 'NZ'],
  ['JQ', 'Jetstar Airways', 'Jetstar Airways', 'AU'],
];

export default AIRLINES;
