/** Libreria icone per le attività (tab Attività) — set curato di emoji
 * (niente Lucide qui: le emoji coprono qualunque concetto — palloni,
 * animali specifici, ecc. — che la libreria di icone a linea non ha, e
 * si adattano automaticamente allo stile della piattaforma: iOS su
 * iPhone, il set nativo di Windows/Android nel browser). Organizzato per
 * categoria tematica, usato dal componente IconPicker. Ogni chiave è
 * salvata su `activities.icon`; il nome visibile (tooltip, ricerca) vive
 * in `activity.iconName.<key>` nei file di traduzione. */

export interface ActivityIconGroup {
  key: string;
  icons: readonly string[];
}

export const ACTIVITY_ICON_GROUPS: readonly ActivityIconGroup[] = [
  {
    key: 'animals',
    icons: [
      'paw-print',
      'bird',
      'fish',
      'whale',
      'rabbit',
      'bug',
      'butterfly',
      'turtle',
      'cat',
      'dog',
      'squirrel',
      'shell',
    ],
  },
  {
    key: 'nature',
    icons: [
      'mountain',
      'forest',
      'pine-tree',
      'sunrise',
      'sunset',
      'flower',
      'tulip',
      'leaf',
      'palm-tree',
      'beach',
      'waterfall',
      'volcano',
      'desert',
      'rainbow',
    ],
  },
  {
    key: 'attractions',
    icons: ['landmark', 'castle', 'church', 'art', 'book', 'theatre', 'building', 'camera', 'star'],
  },
  {
    key: 'food',
    icons: [
      'restaurant',
      'coffee',
      'wine',
      'beer',
      'pizza',
      'ice-cream',
      'cake',
      'soup',
      'sandwich',
      'cherry',
      'apple',
      'croissant',
      'sushi',
      'noodles',
      'taco',
    ],
  },
  {
    key: 'sport',
    icons: [
      'bike',
      'hiking',
      'gym',
      'volleyball',
      'basketball',
      'baseball',
      'soccer',
      'football',
      'tennis',
      'golf',
      'swimming',
      'surfing',
      'skiing',
      'running',
      'yoga',
      'anchor',
      'sailboat',
      'target',
      'medal',
      'trophy',
      'fencing',
      'tent',
      'compass',
    ],
  },
  {
    key: 'beachRelax',
    icons: ['waves', 'beach-umbrella', 'spa', 'life-buoy', 'sun', 'partly-cloudy', 'snow', 'wind', 'rain'],
  },
  {
    key: 'events',
    icons: [
      'party',
      'music',
      'concert',
      'cinema',
      'gaming',
      'ferris-wheel',
      'disco',
      'sparkles',
      'gift',
      'celebration',
    ],
  },
  {
    key: 'transport',
    icons: ['car', 'bus', 'train', 'plane', 'ship', 'fuel', 'parking', 'map', 'road', 'taxi'],
  },
  {
    key: 'shopping',
    icons: ['shopping-bag', 'cart', 'jewelry', 'clothing', 'watch'],
  },
  {
    key: 'nightlife',
    icons: ['moon', 'cocktails'],
  },
  {
    key: 'other',
    icons: ['health', 'rest', 'temperature', 'tag', 'place', 'milestone', 'ticket', 'writing'],
  },
] as const;

export const ACTIVITY_ICON_MAP: Record<string, string> = {
  'paw-print': '🐾',
  bird: '🐦',
  fish: '🐟',
  whale: '🐋',
  rabbit: '🐰',
  bug: '🐛',
  butterfly: '🦋',
  turtle: '🐢',
  cat: '🐱',
  dog: '🐶',
  squirrel: '🐿️',
  shell: '🐚',
  mountain: '⛰️',
  forest: '🌳',
  'pine-tree': '🌲',
  sunrise: '🌅',
  sunset: '🌇',
  flower: '🌸',
  tulip: '🌷',
  leaf: '🍃',
  'palm-tree': '🌴',
  beach: '🏖️',
  waterfall: '🌊',
  volcano: '🌋',
  desert: '🏜️',
  rainbow: '🌈',
  landmark: '🏛️',
  castle: '🏰',
  church: '⛪',
  art: '🎨',
  book: '📖',
  theatre: '🎭',
  building: '🏢',
  camera: '📷',
  star: '⭐',
  restaurant: '🍽️',
  coffee: '☕',
  wine: '🍷',
  beer: '🍺',
  pizza: '🍕',
  'ice-cream': '🍦',
  cake: '🍰',
  soup: '🍲',
  sandwich: '🥪',
  cherry: '🍒',
  apple: '🍎',
  croissant: '🥐',
  sushi: '🍣',
  noodles: '🍜',
  taco: '🌮',
  bike: '🚴',
  hiking: '🥾',
  gym: '🏋️',
  volleyball: '🏐',
  basketball: '🏀',
  baseball: '⚾',
  soccer: '⚽',
  football: '🏈',
  tennis: '🎾',
  golf: '⛳',
  swimming: '🏊',
  surfing: '🏄',
  skiing: '⛷️',
  running: '🏃',
  yoga: '🧘',
  anchor: '⚓',
  sailboat: '⛵',
  target: '🎯',
  medal: '🏅',
  trophy: '🏆',
  fencing: '🤺',
  tent: '⛺',
  compass: '🧭',
  waves: '🌊',
  'beach-umbrella': '⛱️',
  spa: '🧖',
  'life-buoy': '🛟',
  sun: '☀️',
  'partly-cloudy': '⛅',
  snow: '❄️',
  wind: '🌬️',
  rain: '🌧️',
  party: '🎉',
  music: '🎵',
  concert: '🎤',
  cinema: '🎬',
  gaming: '🎮',
  'ferris-wheel': '🎡',
  disco: '🪩',
  sparkles: '✨',
  gift: '🎁',
  celebration: '🎊',
  car: '🚗',
  bus: '🚌',
  train: '🚆',
  plane: '✈️',
  ship: '🚢',
  fuel: '⛽',
  parking: '🅿️',
  map: '🗺️',
  road: '🛣️',
  taxi: '🚕',
  'shopping-bag': '🛍️',
  cart: '🛒',
  jewelry: '💎',
  clothing: '👕',
  watch: '⌚',
  moon: '🌙',
  cocktails: '🍸',
  health: '💊',
  rest: '🛌',
  temperature: '🌡️',
  tag: '🏷️',
  place: '📍',
  milestone: '🏁',
  ticket: '🎫',
  writing: '✍️',
};

export const DEFAULT_ACTIVITY_ICON = 'mountain';

export const resolveActivityIcon = (icon: string | null | undefined): string =>
  (icon && ACTIVITY_ICON_MAP[icon]) || ACTIVITY_ICON_MAP[DEFAULT_ACTIVITY_ICON];
