// ============================================================================
// JourneyAtlas - Alias città → aeroporti
//
// Perché serve: il dataset OurAirports ha i nomi degli aeroporti in inglese e
// il comune in lingua locale ("Milan Malpensa International Airport", comune
// "Ferno"). Un utente italiano digita "Milano" e senza questo strato troverebbe
// solo Linate, perché è l'unico con "Milano" nel nome; "Roma" troverebbe
// "Kostroma Sokerkino Airport".
//
// L'ordine dei codici è l'ordine di utilità per chi parte, non quello
// geografico: per Parigi viene CDG (il grande hub) e non Le Bourget, che pure
// è più vicino al centro. Quando l'utente scrive il nome della città la ricerca
// restituisce esattamente questa sequenza, quindi il primo codice è quello che
// finisce in cima.
//
// Le chiavi sono già piegate: minuscole, senza accenti, senza trattini
// (è la stessa normalizzazione di `foldText`). Ogni alias che si ripete in
// diverse lingue ha una riga sola con entrambe le grafie.
// ============================================================================

/** Città o nome alternativo → codici IATA, dal più usato al meno usato. */
export const CITY_AIRPORT_ALIASES: Record<string, string> = {
  // ── Italia ──
  roma: 'FCO CIA',
  rome: 'FCO CIA',
  milano: 'MXP LIN BGY',
  milan: 'MXP LIN BGY',
  napoli: 'NAP',
  naples: 'NAP',
  torino: 'TRN',
  turin: 'TRN',
  palermo: 'PMO',
  genova: 'GOA',
  genoa: 'GOA',
  bologna: 'BLQ',
  firenze: 'FLR',
  florence: 'FLR',
  venezia: 'VCE',
  venice: 'VCE',
  verona: 'VRN',
  bari: 'BRI',
  catania: 'CTA',
  cagliari: 'CAG',
  trieste: 'TRS',
  perugia: 'PEG',
  rimini: 'RMI',
  pisa: 'PSA',
  ancona: 'AOI',
  lecce: 'LCC',
  bergamo: 'BGY',
  monza: 'MXP LIN BGY',
  como: 'MXP LIN BGY LUG',
  padova: 'VCE',
  padua: 'VCE',
  salerno: 'NAP QSR',
  cosenza: 'SUF',
  livorno: 'PSA',
  siracusa: 'CTA',
  syracuse: 'CTA',
  aosta: 'AOT',
  bolzano: 'BZO',
  bozen: 'BZO',
  trento: 'BZO VRN',
  trent: 'BZO VRN',
  'la spezia': 'PSA GOA',
  sassari: 'AHO OLB',
  pescara: 'PSR',
  'reggio calabria': 'REG',
  varese: 'MXP LIN BGY LUG',
  parma: 'PMF VBS',

  // ── Europa ──
  parigi: 'CDG ORY',
  paris: 'CDG ORY',
  londra: 'LHR LGW STN',
  london: 'LHR LGW STN',
  madrid: 'MAD',
  barcellona: 'BCN',
  barcelona: 'BCN',
  lisbona: 'LIS',
  lisboa: 'LIS',
  lisbon: 'LIS',
  porto: 'OPO',
  amsterdam: 'AMS',
  bruxelles: 'BRU',
  brussels: 'BRU',
  berlino: 'BER',
  berlin: 'BER',
  monaco: 'MUC',
  munich: 'MUC',
  'monaco di baviera': 'MUC',
  francoforte: 'FRA',
  frankfurt: 'FRA',
  vienna: 'VIE',
  wien: 'VIE',
  zurigo: 'ZRH',
  ginevra: 'GVA',
  geneva: 'GVA',
  copenaghen: 'CPH',
  copenhagen: 'CPH',
  stoccolma: 'ARN BMA',
  stockholm: 'ARN BMA',
  oslo: 'OSL',
  dublino: 'DUB',
  dublin: 'DUB',
  atene: 'ATH',
  athens: 'ATH',
  istanbul: 'IST',
  mosca: 'SVO DME VKO',
  moscow: 'SVO DME VKO',
  praga: 'PRG',
  prague: 'PRG',
  budapest: 'BUD',
  bucurest: 'OTP',
  bucharest: 'OTP',
  riga: 'RIX',
  vilnius: 'VNO',
  tallinn: 'TLL',
  kiev: 'KBP IEV',
  kyiv: 'KBP IEV',
  volgograd: 'VOG',
  ekaterinburg: 'SVX',
  novosibirsk: 'OVB',

  // ── Nord America ──
  'new york': 'JFK EWR LGA',
  nyc: 'JFK EWR LGA',
  'los angeles': 'LAX BUR LGB',
  'san francisco': 'SFO OAK SJC',
  seattle: 'SEA',
  boston: 'BOS',
  washington: 'IAD DCA BWI',
  chicago: 'ORD MDW',
  miami: 'MIA FLL',
  atlanta: 'ATL',
  dallas: 'DFW DAL',
  houston: 'IAH HOU',
  denver: 'DEN',
  toronto: 'YYZ',
  montreal: 'YUL',
  vancouver: 'YVR',
  'mexico city': 'MEX',
  'citta del messico': 'MEX',
  honolulu: 'HNL',
  'las vegas': 'LAS',
  orlando: 'MCO SFB',
  cancun: 'CUN',

  // ── Sud America ──
  bogota: 'BOG',
  lima: 'LIM',
  santiago: 'SCL',
  'buenos aires': 'EZE AEP',
  'sao paulo': 'GRU CGH VCP',
  'rio de janeiro': 'GIG SDU',
  rio: 'GIG SDU',

  // ── Africa e Medio Oriente ──
  cairo: 'CAI',
  dubai: 'DXB',
  doha: 'DOH',
  riyadh: 'RUH JED',
  jeddah: 'JED',
  casablanca: 'CMN',
  marrakesh: 'RAK',
  tunisi: 'TUN',
  johannesburg: 'JNB',
  'cape town': 'CPT',
  nairobi: 'NBO',

  // ── Asia e Oceania ──
  tokyo: 'HND NRT',
  osaka: 'KIX ITM',
  seoul: 'ICN GMP',
  beijing: 'PEK PKX',
  pechino: 'PEK PKX',
  shanghai: 'PVG SHA',
  'hong kong': 'HKG',
  taipei: 'TPE',
  bangkok: 'BKK DMK',
  singapore: 'SIN',
  'kuala lumpur': 'KUL',
  jakarta: 'CGK HLP',
  manila: 'MNL',
  delhi: 'DEL',
  'new delhi': 'DEL',
  mumbai: 'BOM',
  bombay: 'BOM',
  sydney: 'SYD',
  melbourne: 'MEL',
  auckland: 'AKL',
  bali: 'DPS',

  // ── Isole e località turistiche ──
  reykjavik: 'KEF',
  faro: 'FAO',
  palma: 'PMI',
  'palma de mallorca': 'PMI',
  ibiza: 'IBZ',
  tenerife: 'TFS TFN',
  lanzarote: 'ACE',
  malta: 'MLA',
  nicosia: 'LCA',
  cipro: 'LCA',
  corfu: 'CFU',
  creta: 'CHQ',
  rhodes: 'RHO',
  rodi: 'RHO',
  santorini: 'JTR',
  mykonos: 'JMK',
  zakynthos: 'ZTH',
  zante: 'ZTH',
  phuket: 'HKT',
};
