export type PhraseCategoryId = 'allergies' | 'needs' | 'emergency' | 'transport' | 'courtesy';

export interface PhraseDef {
  id: string;
  category: PhraseCategoryId;
  it: string;
  en: string;
}

/** Una voce per lingua: [frase nella lingua locale, pronuncia leggibile in italiano]. */
type Entry = readonly [string, string];

export interface PhrasebookLanguage {
  /** Nome inglese della lingua, come lo restituisce REST Countries. */
  name: string;
  rtl?: boolean;
  phrases: Record<string, Entry>;
}

export const PHRASES: PhraseDef[] = [
  { id: 'allergy', category: 'allergies', it: 'Ho una grave allergia alimentare', en: 'I have a severe food allergy' },
  { id: 'gluten', category: 'allergies', it: 'Non posso mangiare glutine', en: "I can't eat gluten" },
  { id: 'dairy', category: 'allergies', it: 'Non posso mangiare latticini', en: "I can't eat dairy" },
  { id: 'nuts', category: 'allergies', it: 'Non posso mangiare frutta secca', en: "I can't eat nuts" },
  { id: 'toilet', category: 'needs', it: "Dov'è il bagno?", en: 'Where is the bathroom?' },
  { id: 'help', category: 'needs', it: 'Ho bisogno di aiuto', en: 'I need help' },
  { id: 'pharmacy', category: 'needs', it: "Dov'è la farmacia?", en: 'Where is the pharmacy?' },
  { id: 'hospital', category: 'needs', it: "Dov'è l'ospedale?", en: 'Where is the hospital?' },
  { id: 'ambulance', category: 'emergency', it: "Chiamate un'ambulanza!", en: 'Call an ambulance!' },
  { id: 'police', category: 'emergency', it: 'Chiamate la polizia!', en: 'Call the police!' },
  { id: 'passport', category: 'emergency', it: 'Ho perso il passaporto', en: 'I lost my passport' },
  { id: 'station', category: 'transport', it: "Dov'è la stazione?", en: 'Where is the station?' },
  { id: 'price', category: 'transport', it: 'Quanto costa?', en: 'How much is it?' },
  { id: 'thanks', category: 'courtesy', it: 'Grazie', en: 'Thank you' },
  { id: 'please', category: 'courtesy', it: 'Per favore', en: 'Please' },
  { id: 'excuse', category: 'courtesy', it: 'Mi scusi', en: 'Excuse me' },
  { id: 'understand', category: 'courtesy', it: 'Non capisco', en: "I don't understand" },
  { id: 'english', category: 'courtesy', it: 'Parla inglese?', en: 'Do you speak English?' },
];

export const PHRASE_CATEGORIES: PhraseCategoryId[] = ['allergies', 'needs', 'emergency', 'transport', 'courtesy'];

export const LANGUAGES: Record<string, PhrasebookLanguage> = {
  en: {
    name: 'English',
    phrases: {
      allergy: ['I have a severe food allergy', 'ai hav a sivìar fud àlerji'],
      gluten: ["I can't eat gluten", 'ai cant it glùten'],
      dairy: ["I can't eat dairy", 'ai cant it dèari'],
      nuts: ["I can't eat nuts", 'ai cant it nats'],
      toilet: ['Where is the bathroom?', 'uèar is da bàsrum'],
      help: ['I need help', 'ai nid elp'],
      pharmacy: ['Where is the pharmacy?', 'uèar is da fàrmasi'],
      hospital: ['Where is the hospital?', 'uèar is da òspital'],
      ambulance: ['Call an ambulance!', 'col an àmbiulans'],
      police: ['Call the police!', 'col da polìs'],
      passport: ['I lost my passport', 'ai lost mai pàsport'],
      station: ['Where is the station?', 'uèar is da stèscion'],
      price: ['How much is it?', 'hau mac is it'],
      thanks: ['Thank you', 'tenk iu'],
      please: ['Please', 'plis'],
      excuse: ['Excuse me', 'ecschiùs mi'],
      understand: ["I don't understand", 'ai dont anderstànd'],
    },
  },
  fr: {
    name: 'French',
    phrases: {
      allergy: ["J'ai une allergie alimentaire grave", 'gé iùn alerjì alimantèr grav'],
      gluten: ['Je ne peux pas manger de gluten', 'ge ne pe pa mangé de glutèn'],
      dairy: ['Je ne peux pas manger de produits laitiers', 'ge ne pe pa mangé de prodùi letié'],
      nuts: ['Je ne peux pas manger de fruits à coque', 'ge ne pe pa mangé de frùi a coc'],
      toilet: ['Où sont les toilettes ?', 'u son le tualèt'],
      help: ["J'ai besoin d'aide", 'gé bezuàn ded'],
      pharmacy: ['Où est la pharmacie ?', 'u è la farmasì'],
      hospital: ["Où est l'hôpital ?", 'u è lopitàl'],
      ambulance: ['Appelez une ambulance !', 'apelé iùn anbiulàns'],
      police: ['Appelez la police !', 'apelé la polìs'],
      passport: ["J'ai perdu mon passeport", 'gé perdù mon paspòr'],
      station: ['Où est la gare ?', 'u è la gar'],
      price: ['Combien ça coûte ?', 'conbién sa cut'],
      thanks: ['Merci', 'mersì'],
      please: ["S'il vous plaît", 'sil vu plè'],
      excuse: ['Excusez-moi', 'ecskiuzé mua'],
      understand: ['Je ne comprends pas', 'ge ne conprán pa'],
      english: ['Parlez-vous anglais ?', 'parlé vu anglè'],
    },
  },
  es: {
    name: 'Spanish',
    phrases: {
      allergy: ['Tengo una alergia alimentaria grave', 'téngo úna alérchia alimentària gràve'],
      gluten: ['No puedo comer gluten', 'no puèdo comèr glùten'],
      dairy: ['No puedo comer lácteos', 'no puèdo comèr làcteos'],
      nuts: ['No puedo comer frutos secos', 'no puèdo comèr frùtos sècos'],
      toilet: ['¿Dónde está el baño?', 'dònde està el bàgno'],
      help: ['Necesito ayuda', 'nesesìto aiùda'],
      pharmacy: ['¿Dónde está la farmacia?', 'dònde està la farmàsia'],
      hospital: ['¿Dónde está el hospital?', 'dònde està el ospitàl'],
      ambulance: ['¡Llame a una ambulancia!', 'iàme a ùna ambulànsia'],
      police: ['¡Llame a la policía!', 'iàme a la polisìa'],
      passport: ['He perdido mi pasaporte', 'e perdìdo mi pasapòrte'],
      station: ['¿Dónde está la estación?', 'dònde està la estasiòn'],
      price: ['¿Cuánto cuesta?', 'cuànto cuèsta'],
      thanks: ['Gracias', 'gràsias'],
      please: ['Por favor', 'por favòr'],
      excuse: ['Disculpe', 'discùlpe'],
      understand: ['No entiendo', 'no entièndo'],
      english: ['¿Habla inglés?', 'àbla inglès'],
    },
  },
  de: {
    name: 'German',
    phrases: {
      allergy: ['Ich habe eine schwere Lebensmittelallergie', 'ic àbe àine scvère lèbensmitelallergì'],
      gluten: ['Ich kann kein Gluten essen', 'ic can cain glùten èssen'],
      dairy: ['Ich kann keine Milchprodukte essen', 'ic can càine milcprodùkte èssen'],
      nuts: ['Ich kann keine Nüsse essen', 'ic can càine nìusse èssen'],
      toilet: ['Wo ist die Toilette?', 'vo ist di tualète'],
      help: ['Ich brauche Hilfe', 'ic bràuhe hilfe'],
      pharmacy: ['Wo ist die Apotheke?', 'vo ist di apotèke'],
      hospital: ['Wo ist das Krankenhaus?', 'vo ist das crànkenhaus'],
      ambulance: ['Rufen Sie einen Krankenwagen!', 'rùfen si àinen crànkenvaghen'],
      police: ['Rufen Sie die Polizei!', 'rùfen si di politsài'],
      passport: ['Ich habe meinen Pass verloren', 'ic àbe màinen pas ferlòren'],
      station: ['Wo ist der Bahnhof?', 'vo ist der bànhof'],
      price: ['Wie viel kostet das?', 'vi fil còstet das'],
      thanks: ['Danke', 'dànke'],
      please: ['Bitte', 'bìte'],
      excuse: ['Entschuldigung', 'entscùldigung'],
      understand: ['Ich verstehe nicht', 'ic ferstèe nict'],
      english: ['Sprechen Sie Englisch?', 'scprèhen si ènglisc'],
    },
  },
  pt: {
    name: 'Portuguese',
    phrases: {
      allergy: ['Tenho uma alergia alimentar grave', 'tégno ùma alerjìa alimentàr gràvi'],
      gluten: ['Não posso comer glúten', 'nãu pòsso comèr glùten'],
      dairy: ['Não posso comer laticínios', 'nãu pòsso comèr latisìnios'],
      nuts: ['Não posso comer frutos secos', 'nãu pòsso comèr frùtos sècos'],
      toilet: ['Onde fica a casa de banho?', 'ònde fìca a càza de bàgno'],
      help: ['Preciso de ajuda', 'presìzu de agiùda'],
      pharmacy: ['Onde fica a farmácia?', 'ònde fìca a farmàsia'],
      hospital: ['Onde fica o hospital?', 'ònde fìca u oscpitàl'],
      ambulance: ['Chame uma ambulância!', 'sciàme ùma ambulànsia'],
      police: ['Chame a polícia!', 'sciàme a polìsia'],
      passport: ['Perdi o meu passaporte', 'perdì u meu pasapòrte'],
      station: ['Onde fica a estação?', 'ònde fìca a ischtasãu'],
      price: ['Quanto custa?', 'quàntu cùsta'],
      thanks: ['Obrigado / Obrigada', 'obrigàdu / obrigàda'],
      please: ['Por favor', 'por favòr'],
      excuse: ['Com licença', 'com lisènsa'],
      understand: ['Não compreendo', 'nãu comprièndu'],
      english: ['Fala inglês?', 'fàla inglès'],
    },
  },
  el: {
    name: 'Greek',
    phrases: {
      allergy: ['Έχω σοβαρή τροφική αλλεργία', 'èho sovarì trofikì alerghìa'],
      gluten: ['Δεν μπορώ να φάω γλουτένη', 'dhen borò na fào glutèni'],
      dairy: ['Δεν μπορώ να φάω γαλακτοκομικά', 'dhen borò na fào galaktokomikà'],
      nuts: ['Δεν μπορώ να φάω ξηρούς καρπούς', 'dhen borò na fào ksirùs karpùs'],
      toilet: ['Πού είναι η τουαλέτα;', 'pù ìne i tualèta'],
      help: ['Χρειάζομαι βοήθεια', 'hriàzome voìthia'],
      pharmacy: ['Πού είναι το φαρμακείο;', 'pù ìne to farmakìo'],
      hospital: ['Πού είναι το νοσοκομείο;', 'pù ìne to nosokomìo'],
      ambulance: ['Καλέστε ασθενοφόρο!', 'kalèste asthenofòro'],
      police: ['Καλέστε την αστυνομία!', 'kalèste tin astinomìa'],
      passport: ['Έχασα το διαβατήριό μου', 'èhasa to dhiavatìrio mu'],
      station: ['Πού είναι ο σταθμός;', 'pù ìne o stathmòs'],
      price: ['Πόσο κάνει;', 'pòso kàni'],
      thanks: ['Ευχαριστώ', 'efharistò'],
      please: ['Παρακαλώ', 'parakalò'],
      excuse: ['Συγγνώμη', 'signòmi'],
      understand: ['Δεν καταλαβαίνω', 'dhen katalavèno'],
      english: ['Μιλάτε αγγλικά;', 'milàte anglikà'],
    },
  },
  ja: {
    name: 'Japanese',
    phrases: {
      allergy: ['重い食物アレルギーがあります', 'omoi sciocumòtsu arerughì ga arimàsu'],
      gluten: ['グルテンは食べられません', 'gurùten wa taberaremasèn'],
      dairy: ['乳製品は食べられません', 'nyuseihin wa taberaremasèn'],
      nuts: ['ナッツは食べられません', 'nàttsu wa taberaremasèn'],
      toilet: ['トイレはどこですか？', 'toìre wa dòco desu ka'],
      help: ['助けてください', 'tasucète cudasài'],
      pharmacy: ['薬局はどこですか？', 'iakkiòcu wa dòco desu ka'],
      hospital: ['病院はどこですか？', 'bioìn wa dòco desu ka'],
      ambulance: ['救急車を呼んでください！', 'kiukiuscia o iondè cudasài'],
      police: ['警察を呼んでください！', 'keisatsu o iondè cudasài'],
      passport: ['パスポートをなくしました', 'pasupòto o nacushimashìta'],
      station: ['駅はどこですか？', 'èki wa dòco desu ka'],
      price: ['いくらですか？', 'ikura desu ka'],
      thanks: ['ありがとう', 'arigatò'],
      please: ['お願いします', 'onegai scimàsu'],
      excuse: ['すみません', 'sumimasèn'],
      understand: ['わかりません', 'uakarimasèn'],
      english: ['英語を話せますか？', 'eigo o hanasemàsu ka'],
    },
  },
  zh: {
    name: 'Chinese',
    phrases: {
      allergy: ['我有严重的食物过敏', 'uo iou ien-gionh de sci-u guo-min'],
      gluten: ['我不能吃麸质', 'uo bu nenh ci fu-gi'],
      dairy: ['我不能吃乳制品', 'uo bu nenh ci ru-gi-pin'],
      nuts: ['我不能吃坚果', 'uo bu nenh ci ghien-guo'],
      toilet: ['洗手间在哪里？', 'si-sciou-ghien zai na-li'],
      help: ['我需要帮助', 'uo sciu-iao bang-giu'],
      pharmacy: ['药店在哪里？', 'iao-dien zai na-li'],
      hospital: ['医院在哪里？', 'i-iuen zai na-li'],
      ambulance: ['请叫救护车！', 'cing ghiao ghiu-hu-ce'],
      police: ['请叫警察！', 'cing ghiao ghing-cia'],
      passport: ['我的护照丢了', 'uo de hu-giao diu le'],
      station: ['车站在哪里？', 'ce-gian zai na-li'],
      price: ['多少钱？', 'duo-sciao cien'],
      thanks: ['谢谢', 'sie-sie'],
      please: ['请', 'cing'],
      excuse: ['对不起', 'dui bu ci'],
      understand: ['我听不懂', 'uo ting bu dong'],
      english: ['你会说英语吗？', 'ni huei suo ing-iu ma'],
    },
  },
  ko: {
    name: 'Korean',
    phrases: {
      allergy: ['심한 음식 알레르기가 있어요', 'simhàn ùmsic allerùghi ga issòio'],
      gluten: ['글루텐을 먹을 수 없어요', 'ghellutenùl mogùl su obsòio'],
      dairy: ['유제품을 먹을 수 없어요', 'iugepumùl mogùl su obsòio'],
      nuts: ['견과류를 먹을 수 없어요', 'ghiongguaryurùl mogùl su obsòio'],
      toilet: ['화장실이 어디예요?', 'hvagiangsiri odiièio'],
      help: ['도와주세요', 'doua giusèio'],
      pharmacy: ['약국이 어디예요?', 'iakkughi odiièio'],
      hospital: ['병원이 어디예요?', 'biongonì odiièio'],
      ambulance: ['구급차를 불러 주세요!', 'gugupciarùl bullò giusèio'],
      police: ['경찰을 불러 주세요!', 'ghiongciarùl bullò giusèio'],
      passport: ['여권을 잃어버렸어요', 'iogonùl irobòriossòio'],
      station: ['역이 어디예요?', 'iogi odiièio'],
      price: ['얼마예요?', 'olmaièio'],
      thanks: ['감사합니다', 'gamsahamnida'],
      please: ['부탁합니다', 'butakamnida'],
      excuse: ['실례합니다', 'sillièhamnida'],
      understand: ['이해하지 못해요', 'ihèhagi motèio'],
      english: ['영어 할 수 있어요?', 'ionò hal su issòio'],
    },
  },
  th: {
    name: 'Thai',
    phrases: {
      allergy: ['ฉันแพ้อาหารอย่างรุนแรง', 'cian pè ahàn iàng runrèng'],
      gluten: ['ฉันกินกลูเตนไม่ได้', 'cian ghin gluten mài dài'],
      dairy: ['ฉันกินผลิตภัณฑ์นมไม่ได้', 'cian ghin plitapàn nom mài dài'],
      nuts: ['ฉันกินถั่วไม่ได้', 'cian ghin tùa mài dài'],
      toilet: ['ห้องน้ำอยู่ที่ไหน', 'hòng nám iù tì nài'],
      help: ['ช่วยด้วย', 'ciuai dùai'],
      pharmacy: ['ร้านขายยาอยู่ที่ไหน', 'ràn cài ia iù tì nài'],
      hospital: ['โรงพยาบาลอยู่ที่ไหน', 'rong pa-iabàn iù tì nài'],
      ambulance: ['เรียกรถพยาบาลหน่อย', 'rìak rót pa-iabàn nòi'],
      police: ['เรียกตำรวจหน่อย', 'rìak tamrùat nòi'],
      passport: ['หนังสือเดินทางหาย', 'nangsù dentang hài'],
      station: ['สถานีอยู่ที่ไหน', 'sa-tàni iù tì nài'],
      price: ['เท่าไหร่', 'tào rài'],
      thanks: ['ขอบคุณ', 'còp cun'],
      please: ['กรุณา', 'garunà'],
      excuse: ['ขอโทษ', 'co tòt'],
      understand: ['ฉันไม่เข้าใจ', 'cian mài cào giai'],
      english: ['พูดภาษาอังกฤษได้ไหม', 'pùt pasà angrìt dài mài'],
    },
  },
  ar: {
    name: 'Arabic',
    rtl: true,
    phrases: {
      allergy: ['لدي حساسية غذائية شديدة', 'ladàia hassasìia ghidhaìia sciadìda'],
      gluten: ['لا أستطيع أكل الغلوتين', 'la astatìa acl al-glutìn'],
      dairy: ['لا أستطيع أكل منتجات الألبان', 'la astatìa acl muntagiàt al-albàn'],
      nuts: ['لا أستطيع أكل المكسرات', 'la astatìa acl al-mucassaràt'],
      toilet: ['أين الحمام؟', 'àina al-hammàm'],
      help: ['أحتاج إلى مساعدة', 'àhtag ila musàada'],
      pharmacy: ['أين الصيدلية؟', 'àina as-saidalìia'],
      hospital: ['أين المستشفى؟', 'àina al-mustasciàfa'],
      ambulance: ['اتصلوا بالإسعاف!', 'ittasilu bil-isàaf'],
      police: ['اتصلوا بالشرطة!', 'ittasilu bi-sciùrta'],
      passport: ['فقدت جواز سفري', 'faqàdtu giawàz safàri'],
      station: ['أين المحطة؟', 'àina al-mahàtta'],
      price: ['كم السعر؟', 'cam as-sìr'],
      thanks: ['شكراً', 'sciùcran'],
      please: ['من فضلك', 'min fàdlic'],
      excuse: ['عفواً', 'àfwan'],
      understand: ['لا أفهم', 'la àfham'],
      english: ['هل تتكلم الإنجليزية؟', 'hal tatakàllam al-inglizìia'],
    },
  },
};

/** Lingue del frasario disponibili, a partire dai nomi inglesi di REST Countries. */
export const phrasebookLanguagesFor = (languageNames: string[]): { code: string; lang: PhrasebookLanguage }[] =>
  Object.entries(LANGUAGES)
    .filter(([, lang]) => languageNames.some((n) => n === lang.name || n.startsWith(`${lang.name} `)))
    .map(([code, lang]) => ({ code, lang }));
