export type PhraseCategoryId = 'allergies' | 'food' | 'needs' | 'emergency' | 'transport' | 'greetings' | 'courtesy';

export interface PhraseDef {
  id: string;
  category: PhraseCategoryId;
  it: string;
  en: string;
}

/** Una voce per lingua: [frase nella lingua locale, pronuncia leggibile in italiano]. */
type Entry = readonly [string, string];

export interface PhrasebookLanguage {
  /** Nome inglese della lingua, come lo restituisce REST Countries. */
  name: string;
  rtl?: boolean;
  /** Variante regionale di un'altra lingua del frasario: non si sceglie dal nome, ma dal paese. */
  variantOf?: string;
  phrases: Record<string, Entry>;
}

export const PHRASES: PhraseDef[] = [
  { id: 'vegetarian', category: 'allergies', it: 'Sono vegetariano/a', en: 'I am vegetarian' },
  { id: 'vegan', category: 'allergies', it: 'Sono vegano/a', en: 'I am vegan' },
  { id: 'allergy', category: 'allergies', it: 'Ho una grave allergia alimentare', en: 'I have a severe food allergy' },
  { id: 'gluten', category: 'allergies', it: 'Non posso mangiare glutine', en: "I can't eat gluten" },
  { id: 'dairy', category: 'allergies', it: 'Non posso mangiare latticini', en: "I can't eat dairy" },
  { id: 'nuts', category: 'allergies', it: 'Non posso mangiare frutta secca', en: "I can't eat nuts" },
  { id: 'meat', category: 'food', it: 'Carne', en: 'Meat' },
  { id: 'beef', category: 'food', it: 'Manzo', en: 'Beef' },
  { id: 'pork', category: 'food', it: 'Maiale', en: 'Pork' },
  { id: 'chicken', category: 'food', it: 'Pollo', en: 'Chicken' },
  { id: 'fish', category: 'food', it: 'Pesce', en: 'Fish' },
  { id: 'shellfish', category: 'food', it: 'Frutti di mare', en: 'Seafood' },
  { id: 'eggs', category: 'food', it: 'Uova', en: 'Eggs' },
  { id: 'rice', category: 'food', it: 'Riso', en: 'Rice' },
  { id: 'bread', category: 'food', it: 'Pane', en: 'Bread' },
  { id: 'vegetables', category: 'food', it: 'Verdure', en: 'Vegetables' },
  { id: 'fruit', category: 'food', it: 'Frutta', en: 'Fruit' },
  { id: 'water', category: 'food', it: 'Acqua', en: 'Water' },
  { id: 'toilet', category: 'needs', it: "Dov'è il bagno?", en: 'Where is the bathroom?' },
  { id: 'help', category: 'needs', it: 'Ho bisogno di aiuto', en: 'I need help' },
  { id: 'pharmacy', category: 'needs', it: "Dov'è la farmacia?", en: 'Where is the pharmacy?' },
  { id: 'hospital', category: 'needs', it: "Dov'è l'ospedale?", en: 'Where is the hospital?' },
  { id: 'price', category: 'needs', it: 'Quanto costa?', en: 'How much is it?' },
  { id: 'ambulance', category: 'emergency', it: "Chiamate un'ambulanza!", en: 'Call an ambulance!' },
  { id: 'police', category: 'emergency', it: 'Chiamate la polizia!', en: 'Call the police!' },
  { id: 'passport', category: 'emergency', it: 'Ho perso il passaporto', en: 'I lost my passport' },
  { id: 'airport', category: 'transport', it: "Dov'è l'aeroporto?", en: 'Where is the airport?' },
  { id: 'station', category: 'transport', it: "Dov'è la stazione?", en: 'Where is the station?' },
  { id: 'hello', category: 'greetings', it: 'Ciao', en: 'Hi' },
  { id: 'hellofm', category: 'greetings', it: 'Salve', en: 'Hello' },
  { id: 'goodbye', category: 'greetings', it: 'Arrivederci', en: 'Goodbye' },
  { id: 'morning', category: 'greetings', it: 'Buongiorno', en: 'Good morning' },
  { id: 'evening', category: 'greetings', it: 'Buonasera', en: 'Good evening' },
  { id: 'night', category: 'greetings', it: 'Buonanotte', en: 'Good night' },
  { id: 'thanks', category: 'courtesy', it: 'Grazie', en: 'Thank you' },
  { id: 'please', category: 'courtesy', it: 'Per favore', en: 'Please' },
  { id: 'excuse', category: 'courtesy', it: 'Mi scusi', en: 'Excuse me' },
  { id: 'understand', category: 'courtesy', it: 'Non capisco', en: "I don't understand" },
  { id: 'english', category: 'courtesy', it: 'Parla inglese?', en: 'Do you speak English?' },
];

export const PHRASE_CATEGORIES: PhraseCategoryId[] = ['allergies', 'food', 'needs', 'emergency', 'transport', 'greetings', 'courtesy'];

export const LANGUAGES: Record<string, PhrasebookLanguage> = {
  en: {
    name: 'English',
    phrases: {
      allergy: ['I have a severe food allergy', 'ai hav a sivìar fud àlerji'],
      gluten: ["I can't eat gluten", 'ai cant it glùten'],
      dairy: ["I can't eat dairy", 'ai cant it dèari'],
      nuts: ["I can't eat nuts", 'ai cant it nats'],
      toilet: ['Where is the bathroom?', 'uèar is de bàsrum'],
      help: ['I need help', 'ai nid elp'],
      pharmacy: ['Where is the pharmacy?', 'uèar is de fàrmasi'],
      hospital: ['Where is the hospital?', 'uèar is de òspital'],
      ambulance: ['Call an ambulance!', 'col an àmbiulans'],
      police: ['Call the police!', 'col de polìs'],
      passport: ['I lost my passport', 'ai lost mai pàsport'],
      station: ['Where is the station?', 'uèar is de stèscion'],
      price: ['How much is it?', 'hau mac is it'],
      thanks: ['Thank you', 'tenk iu'],
      please: ['Please', 'plis'],
      excuse: ['Excuse me', 'ecschiùs mi'],
      understand: ["I don't understand", 'ai dont anderstànd'],
      meat: ['Meat', 'mit'],
      beef: ['Beef', 'bif'],
      pork: ['Pork', 'pork'],
      chicken: ['Chicken', 'cìchen'],
      fish: ['Fish', 'fish'],
      shellfish: ['Seafood', 'sìfud'],
      eggs: ['Eggs', 'egz'],
      rice: ['Rice', 'rais'],
      bread: ['Bread', 'bred'],
      vegetables: ['Vegetables', 'vèggetabols'],
      fruit: ['Fruit', 'frut'],
      water: ['Water', 'uòter'],
      vegetarian: ['I am vegetarian', 'ai am vegetèrian'],
      vegan: ['I am vegan', 'ai am vìgan'],
      hello: ['Hi', 'hai'],
      hellofm: ['Hello', 'helò'],
      goodbye: ['Goodbye', 'gudbài'],
      morning: ['Good morning', 'gud mòrning'],
      evening: ['Good evening', 'gud ìvning'],
      night: ['Good night', 'gud nait'],
      airport: ['Where is the airport?', 'uèar is di èrport'],
    },
  },
  fr: {
    name: 'French',
    phrases: {
      allergy: ["J'ai une allergie alimentaire grave", 'gé iùn alerjì alimantèr grav'],
      gluten: ['Je ne peux pas manger de gluten', 'ge ne pe pa mangé de glutèn'],
      dairy: ['Je ne peux pas manger de produits laitiers', 'ge ne pe pa mangé de prodùi letié'],
      nuts: ['Je ne peux pas manger de fruits à coque', 'ge ne pe pa mangé de frùi a coc'],
      toilet: ['Où sont les toilettes ?', 'u son le tualèt'],
      help: ["J'ai besoin d'aide", 'gé bezuàn ded'],
      pharmacy: ['Où est la pharmacie ?', 'u è la farmasì'],
      hospital: ["Où est l'hôpital ?", 'u è lopitàl'],
      ambulance: ['Appelez une ambulance !', 'apelé iùn anbiulàns'],
      police: ['Appelez la police !', 'apelé la polìs'],
      passport: ["J'ai perdu mon passeport", 'gé perdù mon paspòr'],
      station: ['Où est la gare ?', 'u è la gar'],
      price: ['Combien ça coûte ?', 'conbién sa cut'],
      thanks: ['Merci', 'mersì'],
      please: ["S'il vous plaît", 'sil vu plè'],
      excuse: ['Excusez-moi', 'ecskiuzé mua'],
      understand: ['Je ne comprends pas', 'ge ne conprán pa'],
      english: ['Parlez-vous anglais ?', 'parlé vu anglè'],
      meat: ['Viande', 'viànd'],
      beef: ['Bœuf', 'beuf'],
      pork: ['Porc', 'por'],
      chicken: ['Poulet', 'pulé'],
      fish: ['Poisson', 'puasòn'],
      shellfish: ['Fruits de mer', 'frùi de mèr'],
      eggs: ['Œufs', 'e'],
      rice: ['Riz', 'ri'],
      bread: ['Pain', 'pen'],
      vegetables: ['Légumes', 'legùm'],
      fruit: ['Fruits', 'frùi'],
      water: ['Eau', 'o'],
      vegetarian: ['Je suis végétarien(ne)', 'ge sùi vegetariàn'],
      vegan: ['Je suis vegan', 'ge sùi vegàn'],
      hello: ['Salut', 'salù'],
      hellofm: ['Bonjour', 'bongiùr'],
      goodbye: ['Au revoir', 'o revuàr'],
      morning: ['Bonjour', 'bongiùr'],
      evening: ['Bonsoir', 'bonsuàr'],
      night: ['Bonne nuit', 'bon nùi'],
      airport: ['Où est l\'aéroport ?', 'u è laeropòr'],
    },
  },
  es: {
    name: 'Spanish',
    phrases: {
      allergy: ['Tengo una alergia alimentaria grave', 'téngo úna alérchia alimentària gràve'],
      gluten: ['No puedo comer gluten', 'no puèdo comèr glùten'],
      dairy: ['No puedo comer lácteos', 'no puèdo comèr làcteos'],
      nuts: ['No puedo comer frutos secos', 'no puèdo comèr frùtos sècos'],
      toilet: ['¿Dónde está el baño?', 'dònde està el bàgno'],
      help: ['Necesito ayuda', 'nesesìto aiùda'],
      pharmacy: ['¿Dónde está la farmacia?', 'dònde està la farmàsia'],
      hospital: ['¿Dónde está el hospital?', 'dònde està el ospitàl'],
      ambulance: ['¡Llame a una ambulancia!', 'iàme a ùna ambulànsia'],
      police: ['¡Llame a la policía!', 'iàme a la polisìa'],
      passport: ['He perdido mi pasaporte', 'e perdìdo mi pasapòrte'],
      station: ['¿Dónde está la estación?', 'dònde està la estasiòn'],
      price: ['¿Cuánto cuesta?', 'cuànto cuèsta'],
      thanks: ['Gracias', 'gràsias'],
      please: ['Por favor', 'por favòr'],
      excuse: ['Disculpe', 'discùlpe'],
      understand: ['No entiendo', 'no entièndo'],
      english: ['¿Habla inglés?', 'àbla inglès'],
      meat: ['Carne', 'càrne'],
      beef: ['Ternera', 'ternèra'],
      pork: ['Cerdo', 'sèrdo'],
      chicken: ['Pollo', 'pòio'],
      fish: ['Pescado', 'peskàdo'],
      shellfish: ['Mariscos', 'marìskos'],
      eggs: ['Huevos', 'uèvos'],
      rice: ['Arroz', 'aròs'],
      bread: ['Pan', 'pan'],
      vegetables: ['Verduras', 'verdùras'],
      fruit: ['Fruta', 'frùta'],
      water: ['Agua', 'àgua'],
      vegetarian: ['Soy vegetariano/a', 'soi vegetariàno/a'],
      vegan: ['Soy vegano/a', 'soi vegàno/a'],
      hello: ['Hola', 'òla'],
      hellofm: ['Buenas', 'buènas'],
      goodbye: ['Adiós', 'adiòs'],
      morning: ['Buenos días', 'buènos dìas'],
      evening: ['Buenas tardes', 'buènas tàrdes'],
      night: ['Buenas noches', 'buènas nòces'],
      airport: ['¿Dónde está el aeropuerto?', 'dònde està el aeropuèrto'],
    },
  },
  de: {
    name: 'German',
    phrases: {
      allergy: ['Ich habe eine schwere Lebensmittelallergie', 'ic àbe àine scvère lèbensmitelallergì'],
      gluten: ['Ich kann kein Gluten essen', 'ic can cain glùten èssen'],
      dairy: ['Ich kann keine Milchprodukte essen', 'ic can càine milcprodùkte èssen'],
      nuts: ['Ich kann keine Nüsse essen', 'ic can càine nìusse èssen'],
      toilet: ['Wo ist die Toilette?', 'vo ist di tualète'],
      help: ['Ich brauche Hilfe', 'ic bràuhe hilfe'],
      pharmacy: ['Wo ist die Apotheke?', 'vo ist di apotèke'],
      hospital: ['Wo ist das Krankenhaus?', 'vo ist das crànkenhaus'],
      ambulance: ['Rufen Sie einen Krankenwagen!', 'rùfen si àinen crànkenvaghen'],
      police: ['Rufen Sie die Polizei!', 'rùfen si di politsài'],
      passport: ['Ich habe meinen Pass verloren', 'ic àbe màinen pas ferlòren'],
      station: ['Wo ist der Bahnhof?', 'vo ist der bànhof'],
      price: ['Wie viel kostet das?', 'vi fil còstet das'],
      thanks: ['Danke', 'dànke'],
      please: ['Bitte', 'bìte'],
      excuse: ['Entschuldigung', 'entscùldigung'],
      understand: ['Ich verstehe nicht', 'ic ferstèe nict'],
      english: ['Sprechen Sie Englisch?', 'scprèhen si ènglisc'],
      meat: ['Fleisch', 'flaisc'],
      beef: ['Rindfleisch', 'rìntflaisc'],
      pork: ['Schweinefleisch', 'scvàine-flaisc'],
      chicken: ['Hähnchen', 'hènchen'],
      fish: ['Fisch', 'fisc'],
      shellfish: ['Meeresfrüchte', 'mèresfriùchte'],
      eggs: ['Eier', 'àier'],
      rice: ['Reis', 'rais'],
      bread: ['Brot', 'brot'],
      vegetables: ['Gemüse', 'ghemìuze'],
      fruit: ['Obst', 'obst'],
      water: ['Wasser', 'vàsser'],
      vegetarian: ['Ich bin Vegetarier(in)', 'ic bin vegetàrier(in)'],
      vegan: ['Ich bin Veganer(in)', 'ic bin vegàner(in)'],
      hello: ['Hallo', 'hàlo'],
      hellofm: ['Guten Tag', 'gùten tag'],
      goodbye: ['Auf Wiedersehen', 'auf vìderzen'],
      morning: ['Guten Morgen', 'gùten mòrghen'],
      evening: ['Guten Abend', 'gùten àbent'],
      night: ['Gute Nacht', 'gùte nacht'],
      airport: ['Wo ist der Flughafen?', 'vo ist der flùghafen'],
    },
  },
  pt: {
    name: 'Portuguese',
    phrases: {
      allergy: ['Tenho uma alergia alimentar grave', 'tégno ùma alerjìa alimentàr gràvi'],
      gluten: ['Não posso comer glúten', 'nãu pòsso comèr glùten'],
      dairy: ['Não posso comer laticínios', 'nãu pòsso comèr latisìnios'],
      nuts: ['Não posso comer frutos secos', 'nãu pòsso comèr frùtos sècos'],
      toilet: ['Onde fica a casa de banho?', 'ònde fìca a càza de bàgno'],
      help: ['Preciso de ajuda', 'presìzu de agiùda'],
      pharmacy: ['Onde fica a farmácia?', 'ònde fìca a farmàsia'],
      hospital: ['Onde fica o hospital?', 'ònde fìca u oscpitàl'],
      ambulance: ['Chame uma ambulância!', 'sciàme ùma ambulànsia'],
      police: ['Chame a polícia!', 'sciàme a polìsia'],
      passport: ['Perdi o meu passaporte', 'perdì u meu pasapòrte'],
      station: ['Onde fica a estação?', 'ònde fìca a ischtasãu'],
      price: ['Quanto custa?', 'quàntu cùsta'],
      thanks: ['Obrigado / Obrigada', 'obrigàdu / obrigàda'],
      please: ['Por favor', 'por favòr'],
      excuse: ['Com licença', 'com lisènsa'],
      understand: ['Não compreendo', 'nãu comprièndu'],
      english: ['Fala inglês?', 'fàla inglès'],
      meat: ['Carne', 'càrne'],
      beef: ['Carne de vaca', 'càrne de vàca'],
      pork: ['Porco', 'pòrcu'],
      chicken: ['Frango', 'frànghu'],
      fish: ['Peixe', 'pèisce'],
      shellfish: ['Frutos do mar', 'frùtus du mar'],
      eggs: ['Ovos', 'òvus'],
      rice: ['Arroz', 'arròs'],
      bread: ['Pão', 'pau'],
      vegetables: ['Legumes', 'legùmes'],
      fruit: ['Fruta', 'frùta'],
      water: ['Água', 'àgua'],
      vegetarian: ['Sou vegetariano/a', 'sou vegetarìanu/a'],
      vegan: ['Sou vegano/a', 'sou vegànu/a'],
      hello: ['Oi', 'oi'],
      hellofm: ['Olá', 'olà'],
      goodbye: ['Adeus', 'adèus'],
      morning: ['Bom dia', 'bom dìa'],
      evening: ['Boa tarde', 'bòa tàrde'],
      night: ['Boa noite', 'bòa nòite'],
      airport: ['Onde fica o aeroporto?', 'ònde fìca u aeropòrtu'],
    },
  },
  el: {
    name: 'Greek',
    phrases: {
      allergy: ['Έχω σοβαρή τροφική αλλεργία', 'èho sovarì trofikì alerghìa'],
      gluten: ['Δεν μπορώ να φάω γλουτένη', 'dhen borò na fào glutèni'],
      dairy: ['Δεν μπορώ να φάω γαλακτοκομικά', 'dhen borò na fào galaktokomikà'],
      nuts: ['Δεν μπορώ να φάω ξηρούς καρπούς', 'dhen borò na fào ksirùs karpùs'],
      toilet: ['Πού είναι η τουαλέτα;', 'pù ìne i tualèta'],
      help: ['Χρειάζομαι βοήθεια', 'hriàzome voìthia'],
      pharmacy: ['Πού είναι το φαρμακείο;', 'pù ìne to farmakìo'],
      hospital: ['Πού είναι το νοσοκομείο;', 'pù ìne to nosokomìo'],
      ambulance: ['Καλέστε ασθενοφόρο!', 'kalèste asthenofòro'],
      police: ['Καλέστε την αστυνομία!', 'kalèste tin astinomìa'],
      passport: ['Έχασα το διαβατήριό μου', 'èhasa to dhiavatìrio mu'],
      station: ['Πού είναι ο σταθμός;', 'pù ìne o stathmòs'],
      price: ['Πόσο κάνει;', 'pòso kàni'],
      thanks: ['Ευχαριστώ', 'efharistò'],
      please: ['Παρακαλώ', 'parakalò'],
      excuse: ['Συγγνώμη', 'signòmi'],
      understand: ['Δεν καταλαβαίνω', 'dhen katalavèno'],
      english: ['Μιλάτε αγγλικά;', 'milàte anglikà'],
      meat: ['Κρέας', 'kréas'],
      beef: ['Βοδινό', 'vodinò'],
      pork: ['Χοιρινό', 'chirinò'],
      chicken: ['Κοτόπουλο', 'kotòpulo'],
      fish: ['Ψάρι', 'psàri'],
      shellfish: ['Θαλασσινά', 'thalassinà'],
      eggs: ['Αυγά', 'avgà'],
      rice: ['Ρύζι', 'rìzi'],
      bread: ['Ψωμί', 'psomì'],
      vegetables: ['Λαχανικά', 'lachanikà'],
      fruit: ['Φρούτα', 'frùta'],
      water: ['Νερό', 'nerò'],
      vegetarian: ['Είμαι χορτοφάγος', 'ìme chortofàgos'],
      vegan: ['Είμαι βίγκαν', 'ìme vìgan'],
      hello: ['Γεια', 'ghia'],
      hellofm: ['Γεια σας', 'ghia sas'],
      goodbye: ['Αντίο', 'adìo'],
      morning: ['Καλημέρα', 'kaliméra'],
      evening: ['Καλησπέρα', 'kalispéra'],
      night: ['Καληνύχτα', 'kalinìchta'],
      airport: ['Πού είναι το αεροδρόμιο;', 'pù ìne to aerodròmio'],
    },
  },
  ja: {
    name: 'Japanese',
    phrases: {
      allergy: ['重い食物アレルギーがあります', 'omoi sciocumòtsu arerughì ga arimàsu'],
      gluten: ['グルテンは食べられません', 'gurùten wa taberaremasèn'],
      dairy: ['乳製品は食べられません', 'nyuseihin wa taberaremasèn'],
      nuts: ['ナッツは食べられません', 'nàttsu wa taberaremasèn'],
      toilet: ['トイレはどこですか？', 'toìre wa dòco desu ka'],
      help: ['助けてください', 'tasucète cudasài'],
      pharmacy: ['薬局はどこですか？', 'iakkiòcu wa dòco desu ka'],
      hospital: ['病院はどこですか？', 'bioìn wa dòco desu ka'],
      ambulance: ['救急車を呼んでください！', 'kiukiuscia o iondè cudasài'],
      police: ['警察を呼んでください！', 'keisatsu o iondè cudasài'],
      passport: ['パスポートをなくしました', 'pasupòto o nacushimashìta'],
      station: ['駅はどこですか？', 'èki wa dòco desu ka'],
      price: ['いくらですか？', 'ikura desu ka'],
      thanks: ['ありがとう', 'arigatò'],
      please: ['お願いします', 'onegai scimàsu'],
      excuse: ['すみません', 'sumimasèn'],
      understand: ['わかりません', 'uakarimasèn'],
      english: ['英語を話せますか？', 'eigo o hanasemàsu ka'],
      meat: ['肉', 'niku'],
      beef: ['牛肉', 'gyùniku'],
      pork: ['豚肉', 'butàniku'],
      chicken: ['鶏肉', 'toriniku'],
      fish: ['魚', 'sakàna'],
      shellfish: ['シーフード', 'scifùdo'],
      eggs: ['卵', 'tamàgo'],
      rice: ['ご飯', 'gohàn'],
      bread: ['パン', 'pan'],
      vegetables: ['野菜', 'iasài'],
      fruit: ['果物', 'kudàmono'],
      water: ['水', 'mizu'],
      vegetarian: ['私はベジタリアンです', 'uatashi ua bejitarian desu'],
      vegan: ['私はビーガンです', 'uatashi ua bìgan desu'],
      hello: ['やあ', 'iàa'],
      hellofm: ['こんにちは', 'konnichiua'],
      goodbye: ['さようなら', 'saiònara'],
      morning: ['おはようございます', 'ohaiò gozaimas'],
      evening: ['こんばんは', 'konbanua'],
      night: ['おやすみなさい', 'oiasumi nasài'],
      airport: ['空港はどこですか？', 'kùko wa dòco desu ka'],
    },
  },
  zh: {
    name: 'Chinese',
    phrases: {
      allergy: ['我有严重的食物过敏', 'uo iou ien-gionh de sci-u guo-min'],
      gluten: ['我不能吃麸质', 'uo bu nenh ci fu-gi'],
      dairy: ['我不能吃乳制品', 'uo bu nenh ci ru-gi-pin'],
      nuts: ['我不能吃坚果', 'uo bu nenh ci ghien-guo'],
      toilet: ['洗手间在哪里？', 'si-sciou-ghien zai na-li'],
      help: ['我需要帮助', 'uo sciu-iao bang-giu'],
      pharmacy: ['药店在哪里？', 'iao-dien zai na-li'],
      hospital: ['医院在哪里？', 'i-iuen zai na-li'],
      ambulance: ['请叫救护车！', 'cing ghiao ghiu-hu-ce'],
      police: ['请叫警察！', 'cing ghiao ghing-cia'],
      passport: ['我的护照丢了', 'uo de hu-giao diu le'],
      station: ['车站在哪里？', 'ce-gian zai na-li'],
      price: ['多少钱？', 'duo-sciao cien'],
      thanks: ['谢谢', 'sie-sie'],
      please: ['请', 'cing'],
      excuse: ['对不起', 'dui bu ci'],
      understand: ['我听不懂', 'uo ting bu dong'],
      english: ['你会说英语吗？', 'ni huei suo ing-iu ma'],
      meat: ['肉', 'rou'],
      beef: ['牛肉', 'niù rou'],
      pork: ['猪肉', 'giù rou'],
      chicken: ['鸡肉', 'gi rou'],
      fish: ['鱼', 'iù'],
      shellfish: ['海鲜', 'hài sien'],
      eggs: ['鸡蛋', 'gi dàn'],
      rice: ['米饭', 'mi fàn'],
      bread: ['面包', 'mien bao'],
      vegetables: ['蔬菜', 'sciu tsài'],
      fruit: ['水果', 'sciuèi guo'],
      water: ['水', 'sciuèi'],
      vegetarian: ['我吃素', 'uo ci su'],
      vegan: ['我是纯素食者', 'uo sci ciuén su sci gé'],
      hello: ['你好', 'ni hao'],
      hellofm: ['您好', 'nin hao'],
      goodbye: ['再见', 'dzài ghien'],
      morning: ['早上好', 'dzao sciàng hao'],
      evening: ['晚上好', 'uàn sciàng hao'],
      night: ['晚安', 'uàn an'],
      airport: ['机场在哪里？', 'gi-ciàng zai na-li'],
    },
  },
  ko: {
    name: 'Korean',
    phrases: {
      allergy: ['심한 음식 알레르기가 있어요', 'simhàn ùmsic allerùghi ga issòio'],
      gluten: ['글루텐을 먹을 수 없어요', 'ghellutenùl mogùl su obsòio'],
      dairy: ['유제품을 먹을 수 없어요', 'iugepumùl mogùl su obsòio'],
      nuts: ['견과류를 먹을 수 없어요', 'ghiongguaryurùl mogùl su obsòio'],
      toilet: ['화장실이 어디예요?', 'hvagiangsiri odiièio'],
      help: ['도와주세요', 'doua giusèio'],
      pharmacy: ['약국이 어디예요?', 'iakkughi odiièio'],
      hospital: ['병원이 어디예요?', 'biongonì odiièio'],
      ambulance: ['구급차를 불러 주세요!', 'gugupciarùl bullò giusèio'],
      police: ['경찰을 불러 주세요!', 'ghiongciarùl bullò giusèio'],
      passport: ['여권을 잃어버렸어요', 'iogonùl irobòriossòio'],
      station: ['역이 어디예요?', 'iogi odiièio'],
      price: ['얼마예요?', 'olmaièio'],
      thanks: ['감사합니다', 'gamsahamnida'],
      please: ['부탁합니다', 'butakamnida'],
      excuse: ['실례합니다', 'sillièhamnida'],
      understand: ['이해하지 못해요', 'ihèhagi motèio'],
      english: ['영어 할 수 있어요?', 'ionò hal su issòio'],
      meat: ['고기', 'kogi'],
      beef: ['소고기', 'sogogi'],
      pork: ['돼지고기', 'tuègigogi'],
      chicken: ['닭고기', 'takkogi'],
      fish: ['생선', 'sengsòn'],
      shellfish: ['해산물', 'hesànmul'],
      eggs: ['달걀', 'talghiàl'],
      rice: ['밥', 'pap'],
      bread: ['빵', 'ppang'],
      vegetables: ['채소', 'cheso'],
      fruit: ['과일', 'cuàil'],
      water: ['물', 'mul'],
      vegetarian: ['저는 채식주의자예요', 'ciònun cheshìkciuìgia-ieio'],
      vegan: ['저는 비건이에요', 'ciònun bigòn-ieio'],
      hello: ['안녕', 'annièng'],
      hellofm: ['안녕하세요', 'annièng-haseio'],
      goodbye: ['안녕히 가세요', 'annièng-hi kaseio'],
      morning: ['좋은 아침입니다', 'ciòun achimimnida'],
      evening: ['좋은 저녁입니다', 'ciòun ciònyok imnida'],
      night: ['안녕히 주무세요', 'annièng-hi ciumuseio'],
      airport: ['공항이 어디예요?', 'konghàng-i odiièio'],
    },
  },
  th: {
    name: 'Thai',
    phrases: {
      allergy: ['ฉันแพ้อาหารอย่างรุนแรง', 'cian pè ahàn iàng runrèng'],
      gluten: ['ฉันกินกลูเตนไม่ได้', 'cian ghin gluten mài dài'],
      dairy: ['ฉันกินผลิตภัณฑ์นมไม่ได้', 'cian ghin plitapàn nom mài dài'],
      nuts: ['ฉันกินถั่วไม่ได้', 'cian ghin tùa mài dài'],
      toilet: ['ห้องน้ำอยู่ที่ไหน', 'hòng nám iù tì nài'],
      help: ['ช่วยด้วย', 'ciuai dùai'],
      pharmacy: ['ร้านขายยาอยู่ที่ไหน', 'ràn cài ia iù tì nài'],
      hospital: ['โรงพยาบาลอยู่ที่ไหน', 'rong pa-iabàn iù tì nài'],
      ambulance: ['เรียกรถพยาบาลหน่อย', 'rìak rót pa-iabàn nòi'],
      police: ['เรียกตำรวจหน่อย', 'rìak tamrùat nòi'],
      passport: ['หนังสือเดินทางหาย', 'nangsù dentang hài'],
      station: ['สถานีอยู่ที่ไหน', 'sa-tàni iù tì nài'],
      price: ['เท่าไหร่', 'tào rài'],
      thanks: ['ขอบคุณ', 'còp cun'],
      please: ['กรุณา', 'garunà'],
      excuse: ['ขอโทษ', 'co tòt'],
      understand: ['ฉันไม่เข้าใจ', 'cian mài cào giai'],
      english: ['พูดภาษาอังกฤษได้ไหม', 'pùt pasà angrìt dài mài'],
      meat: ['เนื้อ', 'nùa'],
      beef: ['เนื้อวัว', 'nùa vua'],
      pork: ['หมู', 'mu'],
      chicken: ['ไก่', 'kài'],
      fish: ['ปลา', 'plà'],
      shellfish: ['อาหารทะเล', 'ahàn talè'],
      eggs: ['ไข่', 'khài'],
      rice: ['ข้าว', 'khào'],
      bread: ['ขนมปัง', 'khanòm pang'],
      vegetables: ['ผัก', 'phak'],
      fruit: ['ผลไม้', 'phon-la-mài'],
      water: ['น้ำ', 'nám'],
      vegetarian: ['ฉันเป็นมังสวิรัติ', 'chàn pen mangsawirát'],
      vegan: ['ฉันเป็นวีแกน', 'chàn pen vigèn'],
      hello: ['หวัดดี', 'wàtdi'],
      hellofm: ['สวัสดีครับ/ค่ะ', 'sawàtdi khráp/khà'],
      goodbye: ['ลาก่อน', 'la còn'],
      morning: ['สวัสดีตอนเช้า', 'sawàtdi ton chào'],
      evening: ['สวัสดีตอนเย็น', 'sawàtdi ton jen'],
      night: ['ราตรีสวัสดิ์', 'ratri sawàt'],
      airport: ['สนามบินอยู่ที่ไหน', 'sa-nàm bin iù tì nài'],
    },
  },
  ar: {
    name: 'Arabic',
    rtl: true,
    phrases: {
      allergy: ['لدي حساسية غذائية شديدة', 'ladàia hassasìia ghidhaìia sciadìda'],
      gluten: ['لا أستطيع أكل الغلوتين', 'la astatìa acl al-glutìn'],
      dairy: ['لا أستطيع أكل منتجات الألبان', 'la astatìa acl muntagiàt al-albàn'],
      nuts: ['لا أستطيع أكل المكسرات', 'la astatìa acl al-mucassaràt'],
      toilet: ['أين الحمام؟', 'àina al-hammàm'],
      help: ['أحتاج إلى مساعدة', 'àhtag ila musàada'],
      pharmacy: ['أين الصيدلية؟', 'àina as-saidalìia'],
      hospital: ['أين المستشفى؟', 'àina al-mustasciàfa'],
      ambulance: ['اتصلوا بالإسعاف!', 'ittasilu bil-isàaf'],
      police: ['اتصلوا بالشرطة!', 'ittasilu bi-sciùrta'],
      passport: ['فقدت جواز سفري', 'faqàdtu giawàz safàri'],
      station: ['أين المحطة؟', 'àina al-mahàtta'],
      price: ['كم السعر؟', 'cam as-sìr'],
      thanks: ['شكراً', 'sciùcran'],
      please: ['من فضلك', 'min fàdlic'],
      excuse: ['عفواً', 'àfwan'],
      understand: ['لا أفهم', 'la àfham'],
      english: ['هل تتكلم الإنجليزية؟', 'hal tatakàllam al-inglizìia'],
      meat: ['لحم', 'lahm'],
      beef: ['لحم بقر', 'lahm bàcar'],
      pork: ['لحم خنزير', 'lahm chinzìr'],
      chicken: ['دجاج', 'degiàg'],
      fish: ['سمك', 'sàmac'],
      shellfish: ['مأكولات بحرية', 'maacolàt bahrìia'],
      eggs: ['بيض', 'bàid'],
      rice: ['أرز', 'àruzz'],
      bread: ['خبز', 'chubz'],
      vegetables: ['خضروات', 'chudrawàt'],
      fruit: ['فواكه', 'fawàkih'],
      water: ['ماء', 'maa'],
      vegetarian: ['أنا نباتي', 'ana nabàti'],
      vegan: ['أنا نباتي صرف', 'ana nabàti sarf'],
      hello: ['مرحبا', 'màrhaba'],
      hellofm: ['السلام عليكم', 'as-salàm alàicum'],
      goodbye: ['مع السلامة', 'màa as-salàma'],
      morning: ['صباح الخير', 'sabàh al-chàir'],
      evening: ['مساء الخير', 'masàa al-chàir'],
      night: ['تصبح على خير', 'tusbìh ala chàir'],
      airport: ['أين المطار؟', 'àina al-matàr'],
    },
  },
};

/** Paesi in cui si mostra l'inglese britannico (termini e fonetica) invece di quello americano. */
export const BRITISH_ENGLISH_COUNTRIES = ['GB'];

/** Inglese britannico: parte dall'americano e cambia i termini e la pronuncia che differiscono. */
LANGUAGES['en-gb'] = {
  name: 'English',
  variantOf: 'en',
  phrases: {
    ...LANGUAGES.en.phrases,
    allergy: ['I have a severe food allergy', 'ai hav a sivìa fud àleji'],
    gluten: ["I can't eat gluten", 'ai caant it glùten'],
    dairy: ["I can't eat dairy", 'ai caant it dèeri'],
    nuts: ["I can't eat nuts", 'ai caant it nats'],
    toilet: ['Where is the toilet?', 'uèa is de tòilet'],
    pharmacy: ["Where is the chemist's?", 'uèa is de chèmists'],
    hospital: ['Where is the hospital?', 'uèa is de òspital'],
    airport: ['Where is the airport?', 'uèa is de èapòt'],
    station: ['Where is the station?', 'uèa is de stèscion'],
    police: ['Call the police!', 'col de polìis'],
    passport: ['I lost my passport', 'ai lost mai pàaspot'],
    understand: ["I don't understand", 'ai dont andestànd'],
    pork: ['Pork', 'pòk'],
    water: ['Water', 'uòta'],
    vegetarian: ['I am vegetarian', 'ai am vegitèerian'],
    hellofm: ['Hello', 'helòu'],
    morning: ['Good morning', 'gud mòning'],
    evening: ['Good evening', 'gud ìivning'],
  },
};

/** Italiano, per chi arriva in Italia da un altro paese: la pronuncia è scritta per chi legge inglese
 *  (maiuscolo = sillaba accentata), a differenza delle altre lingue che usano la grafia italiana. */
LANGUAGES.it = {
  name: 'Italian',
  phrases: {
    allergy: ['Ho una grave allergia alimentare', 'oh OO-na GRAH-veh ah-lair-JEE-ah ah-lee-men-TAH-reh'],
    gluten: ['Non posso mangiare glutine', 'non POHS-soh man-JAH-reh GLOO-tee-neh'],
    dairy: ['Non posso mangiare latticini', 'non POHS-soh man-JAH-reh laht-tee-CHEE-nee'],
    nuts: ['Non posso mangiare frutta secca', 'non POHS-soh man-JAH-reh FROOT-tah SEK-kah'],
    toilet: ["Dov'è il bagno?", 'DOH-veh eel BAH-nyoh'],
    help: ['Ho bisogno di aiuto', 'oh bee-ZOH-nyoh dee eye-YOO-toh'],
    pharmacy: ["Dov'è la farmacia?", 'DOH-veh lah far-mah-CHEE-ah'],
    hospital: ["Dov'è l'ospedale?", 'DOH-veh lohs-peh-DAH-leh'],
    ambulance: ["Chiamate un'ambulanza!", 'kyah-MAH-teh oon am-boo-LAHN-tsah'],
    police: ['Chiamate la polizia!', 'kyah-MAH-teh lah poh-lee-TSEE-ah'],
    passport: ['Ho perso il passaporto', 'oh PEHR-soh eel pahs-sah-POR-toh'],
    station: ["Dov'è la stazione?", 'DOH-veh lah stah-TSYOH-neh'],
    airport: ["Dov'è l'aeroporto?", 'DOH-veh lah-eh-roh-POR-toh'],
    price: ['Quanto costa?', 'KWAHN-toh KOH-stah'],
    thanks: ['Grazie', 'GRAH-tsyeh'],
    please: ['Per favore', 'pehr fah-VOH-reh'],
    excuse: ['Mi scusi', 'mee SKOO-zee'],
    understand: ['Non capisco', 'non kah-PEES-koh'],
    english: ['Parla inglese?', 'PAR-lah een-GLEH-zeh'],
    meat: ['Carne', 'KAR-neh'],
    beef: ['Manzo', 'MAHN-dzoh'],
    pork: ['Maiale', 'mah-YAH-leh'],
    chicken: ['Pollo', 'POHL-loh'],
    fish: ['Pesce', 'PEH-sheh'],
    shellfish: ['Frutti di mare', 'FROOT-tee dee MAH-reh'],
    eggs: ['Uova', 'WOH-vah'],
    rice: ['Riso', 'REE-zoh'],
    bread: ['Pane', 'PAH-neh'],
    vegetables: ['Verdure', 'vehr-DOO-reh'],
    fruit: ['Frutta', 'FROOT-tah'],
    water: ['Acqua', 'AHK-kwah'],
    vegetarian: ['Sono vegetariano/a', 'SOH-noh veh-jeh-tah-RYAH-noh'],
    vegan: ['Sono vegano/a', 'SOH-noh veh-GAH-noh'],
    hello: ['Ciao', 'CHOW'],
    hellofm: ['Salve', 'SAHL-veh'],
    goodbye: ['Arrivederci', 'ar-ree-veh-DEHR-chee'],
    morning: ['Buongiorno', 'bwon-JOR-noh'],
    evening: ['Buonasera', 'bwoh-nah-SEH-rah'],
    night: ['Buonanotte', 'bwoh-nah-NOT-teh'],
  },
};

LANGUAGES.ro = {
  name: 'Romanian',
  phrases: {
    allergy: ['Am o alergie alimentară gravă', 'am o alergìe alimentàre gràve'],
    gluten: ['Nu pot mânca gluten', 'nu pot mnca glùten'],
    dairy: ['Nu pot mânca lactate', 'nu pot mnca lactàte'],
    nuts: ['Nu pot mânca nuci', 'nu pot mnca nuc'],
    toilet: ['Unde este toaleta?', 'ùnde ièste toalèta'],
    help: ['Am nevoie de ajutor', 'am nevòie de agiutòr'],
    pharmacy: ['Unde este farmacia?', 'ùnde ièste farmacìa'],
    hospital: ['Unde este spitalul?', 'ùnde ièste spitalul'],
    ambulance: ['Chemați o ambulanță!', 'kemàts o ambulàntse'],
    police: ['Chemați poliția!', 'kemàts polìtsia'],
    passport: ['Mi-am pierdut pașaportul', 'miam pierdùt pasciapòrtul'],
    station: ['Unde este gara?', 'ùnde ièste gàra'],
    airport: ['Unde este aeroportul?', 'ùnde ièste aeropòrtul'],
    price: ['Cât costă?', 'kt còste'],
    thanks: ['Mulțumesc', 'multsumèsc'],
    please: ['Vă rog', 've rog'],
    excuse: ['Scuzați-mă', 'scuzàts-me'],
    understand: ['Nu înțeleg', 'nu ntselèg'],
    english: ['Vorbiți engleză?', 'vorbìts englèze'],
    meat: ['Carne', 'càrne'],
    beef: ['Vită', 'vìte'],
    pork: ['Porc', 'pork'],
    chicken: ['Pui', 'pui'],
    fish: ['Pește', 'pèshte'],
    shellfish: ['Fructe de mare', 'frùcte de màre'],
    eggs: ['Ouă', 'òue'],
    rice: ['Orez', 'orèz'],
    bread: ['Pâine', 'pne'],
    vegetables: ['Legume', 'legùme'],
    fruit: ['Fructe', 'frùcte'],
    water: ['Apă', 'àpe'],
    vegetarian: ['Sunt vegetarian', 'sunt vegetariàn'],
    vegan: ['Sunt vegan', 'sunt vegàn'],
    hello: ['Salut', 'salùt'],
    hellofm: ['Bună ziua', 'bùne zìua'],
    goodbye: ['La revedere', 'la revedère'],
    morning: ['Bună dimineața', 'bùne diminèatsa'],
    evening: ['Bună seara', 'bùne siàra'],
    night: ['Noapte bună', 'noàpte bùne'],
  },
};

LANGUAGES.bg = {
  name: 'Bulgarian',
  phrases: {
    allergy: ['Имам тежка хранителна алергия', 'imàm tèzhka hranìtelna alèrgia'],
    gluten: ['Не мога да ям глутен', 'ne mòga da iam glùten'],
    dairy: ['Не мога да ям млечни продукти', 'ne mòga da iam mlètchni prodùkti'],
    nuts: ['Не мога да ям ядки', 'ne mòga da iam iàtki'],
    toilet: ['Къде е тоалетната?', 'kadè e toalètnata'],
    help: ['Имам нужда от помощ', 'imàm nùzhda ot pòmosht'],
    pharmacy: ['Къде е аптеката?', 'kadè e aptèkata'],
    hospital: ['Къде е болницата?', 'kadè e bòlnitsata'],
    ambulance: ['Извикайте линейка!', 'izvikàite linèika'],
    police: ['Извикайте полиция!', 'izvikàite polìtsia'],
    passport: ['Загубих паспорта си', 'zagùbih pàsporta si'],
    station: ['Къде е гарата?', 'kadè e gàrata'],
    airport: ['Къде е летището?', 'kadè e letìshteto'],
    price: ['Колко струва?', 'kòlko strùva'],
    thanks: ['Благодаря', 'blagodarià'],
    please: ['Моля', 'mòlia'],
    excuse: ['Извинете', 'izvinète'],
    understand: ['Не разбирам', 'ne razbìram'],
    english: ['Говорите ли английски?', 'govorìte li anglìski'],
    meat: ['Месо', 'mesò'],
    beef: ['Говеждо', 'govèzhdo'],
    pork: ['Свинско', 'svìnsko'],
    chicken: ['Пиле', 'pìle'],
    fish: ['Риба', 'rìba'],
    shellfish: ['Морски дарове', 'mòrski darovè'],
    eggs: ['Яйца', 'iàitsa'],
    rice: ['Ориз', 'orìz'],
    bread: ['Хляб', 'hliàp'],
    vegetables: ['Зеленчуци', 'zelentchùtsi'],
    fruit: ['Плодове', 'plodovè'],
    water: ['Вода', 'vodà'],
    vegetarian: ['Аз съм вегетарианец', 'as sam vegetariànets'],
    vegan: ['Аз съм веган', 'as sam vegàn'],
    hello: ['Здрасти', 'zdràsti'],
    hellofm: ['Здравейте', 'zdravèite'],
    goodbye: ['Довиждане', 'dovìzhdane'],
    morning: ['Добро утро', 'dobrò ùtro'],
    evening: ['Добър вечер', 'dòbar vètcher'],
    night: ['Лека нощ', 'lèka nosht'],
  },
};

LANGUAGES.ru = {
  name: 'Russian',
  phrases: {
    allergy: ['У меня сильная пищевая аллергия', 'u menià sìlnaia pìshevaia allèrghia'],
    gluten: ['Мне нельзя глютен', 'mne nelzià glùten'],
    dairy: ['Мне нельзя молочное', 'mne nelzià molòtchnoie'],
    nuts: ['Мне нельзя орехи', 'mne nelzià orèhi'],
    toilet: ['Где туалет?', 'gdie tualèt'],
    help: ['Мне нужна помощь', 'mne nuzhnà pòmosh'],
    pharmacy: ['Где аптека?', 'gdie aptèka'],
    hospital: ['Где больница?', 'gdie bolnìtsa'],
    ambulance: ['Вызовите скорую!', 'vìzovite skòruiu'],
    police: ['Вызовите полицию!', 'vìzovite polìtsiu'],
    passport: ['Я потерял паспорт', 'ia poteriàl pàsport'],
    station: ['Где вокзал?', 'gdie vokzàl'],
    airport: ['Где аэропорт?', 'gdie aeropòrt'],
    price: ['Сколько стоит?', 'skòlko stòit'],
    thanks: ['Спасибо', 'spasìbo'],
    please: ['Пожалуйста', 'pozhàlusta'],
    excuse: ['Извините', 'izvinìte'],
    understand: ['Я не понимаю', 'ia nie ponimàiu'],
    english: ['Вы говорите по-английски?', 'vi govorìte po anglìski'],
    meat: ['Мясо', 'miàso'],
    beef: ['Говядина', 'govìadina'],
    pork: ['Свинина', 'svinìna'],
    chicken: ['Курица', 'kùritsa'],
    fish: ['Рыба', 'rìba'],
    shellfish: ['Морепродукты', 'morepradùkti'],
    eggs: ['Яйца', 'iàitsa'],
    rice: ['Рис', 'ris'],
    bread: ['Хлеб', 'hliep'],
    vegetables: ['Овощи', 'òvoshi'],
    fruit: ['Фрукты', 'frùkti'],
    water: ['Вода', 'vodà'],
    vegetarian: ['Я вегетарианец', 'ia vegetariànets'],
    vegan: ['Я веган', 'ia vegàn'],
    hello: ['Привет', 'privièt'],
    hellofm: ['Здравствуйте', 'zdràstvuite'],
    goodbye: ['До свидания', 'do svidània'],
    morning: ['Доброе утро', 'dòbroie ùtro'],
    evening: ['Добрый вечер', 'dòbri vètcher'],
    night: ['Спокойной ночи', 'spokòinoi nòtchi'],
  },
};

LANGUAGES.hi = {
  name: 'Hindi',
  phrases: {
    allergy: ['मुझे गंभीर खाद्य एलर्जी है', 'mujhe gambhìr khàdya èlarji hai'],
    gluten: ['मैं ग्लूटेन नहीं खा सकता/सकती', 'main glùten nahìn khà sakta/sakti'],
    dairy: ['मैं डेयरी नहीं खा सकता/सकती', 'main dèiri nahìn khà sakta/sakti'],
    nuts: ['मैं मेवे नहीं खा सकता/सकती', 'main mève nahìn khà sakta/sakti'],
    toilet: ['शौचालय कहाँ है?', 'shauchàlay kahàn hai'],
    help: ['मुझे मदद चाहिए', 'mujhe madàd tchahìye'],
    pharmacy: ['दवा की दुकान कहाँ है?', 'davà ki dukàn kahàn hai'],
    hospital: ['अस्पताल कहाँ है?', 'aspatàl kahàn hai'],
    ambulance: ['एम्बुलेंस बुलाइए!', 'èmbulens bulàie'],
    police: ['पुलिस को बुलाइए!', 'pulìs ko bulàie'],
    passport: ['मेरा पासपोर्ट खो गया है', 'mèra pàsport kho gayà hai'],
    station: ['स्टेशन कहाँ है?', 'stèshan kahàn hai'],
    airport: ['हवाई अड्डा कहाँ है?', 'havài addà kahàn hai'],
    price: ['यह कितने का है?', 'yeh kitne kà hai'],
    thanks: ['धन्यवाद', 'dhanyavàd'],
    please: ['कृपया', 'kripayà'],
    excuse: ['माफ़ कीजिए', 'maf kijìye'],
    understand: ['मुझे समझ नहीं आया', 'mujhe samàjh nahìn aya'],
    english: ['क्या आप अंग्रेज़ी बोलते हैं?', 'kyà ap angrezì bolte hain'],
    meat: ['मांस', 'mans'],
    beef: ['गोमांस', 'gomàns'],
    pork: ['सूअर का मांस', 'suàr ka màns'],
    chicken: ['चिकन', 'tchìkan'],
    fish: ['मछली', 'matchhlì'],
    shellfish: ['समुद्री भोजन', 'samudrì bhòjan'],
    eggs: ['अंडे', 'ànde'],
    rice: ['चावल', 'tchàval'],
    bread: ['रोटी', 'rotì'],
    vegetables: ['सब्ज़ियाँ', 'sabziyàn'],
    fruit: ['फल', 'phal'],
    water: ['पानी', 'panì'],
    vegetarian: ['मैं शाकाहारी हूँ', 'main shakahàri hun'],
    vegan: ['मैं वीगन हूँ', 'main vìgan hun'],
    hello: ['नमस्ते', 'namastè'],
    hellofm: ['नमस्कार', 'namaskàr'],
    goodbye: ['अलविदा', 'alvidà'],
    morning: ['शुभ प्रभात', 'shubh prabhàt'],
    evening: ['शुभ संध्या', 'shubh sandhyà'],
    night: ['शुभ रात्रि', 'shubh ràtri'],
  },
};

/** Lingue del frasario disponibili, a partire dai nomi inglesi di REST Countries. */
export const phrasebookLanguagesFor = (languageNames: string[]): { code: string; lang: PhrasebookLanguage }[] =>
  Object.entries(LANGUAGES)
    .filter(([, lang]) => !lang.variantOf && languageNames.some((n) => n === lang.name || n.startsWith(`${lang.name} `)))
    .map(([code, lang]) => ({ code, lang }));
